### ISSUE TITLE
Could not find 'passenger' 

### ISSUE THREAD

**Issue by torreyj** [capistrano/passenger#29]
I updated my version of passenger to 5.0.14, and updated to the latest version of capistrano/passenger. I use rvm, and have the 'rvm_ruby_version' set, along with my 'passenger_rvm_ruby_version' set.  I check on my server that the new restart passenger command works, but when I do a cap deploy, I constantly get 

Could not find 'passenger' (>= 0) among 6 total gem(s)
Gem::LoadError

But when I have it set to 'set :passenger_restart_with_touch, true', it works and no issues.  So obviously there's still something wrong with getting this 'restart' command to work with your gem. Is there setting's I'm missing to get that to run correctly?  Or is this still broke?

**Comment by betesh** [comment]
Show me debug output.  
Show me your Capfile and config/deploy.rb
Where is passenger installed?

**Comment by torreyj** [comment]
The app that is giving me a problems is a ruby 1.9.3 app.  My updated apps that are in ruby 2.2.1 work just fine. I have passenger setup under the global gemset of ruby 2.2.1, which is my default and set as current when you log on to the server. I have my 1.9.3 app setup under its own gemset. As you can see in my deploy files, I set the :rvm_ruby_version to '1.9.3@gemset_name', and my :passenger_restart_ruby_version to '2.2.1'. 

It appears to go to a different GEM_PATH? Maybe something with the bundler? On my server, all the gems are located in a folder path /var/www/sites/sitename/shared/bundle/ruby/1.9.1', but for some reason this keeps going to path '/var/www/sites/sitename/shared/bundle/ruby/2.2.0' in the debug output? Here's the error that gets kicked out. My files are linked below:

```
DEBUG [cf98ff63] Command: cd /var/www/sites/sitename/releases/20150720165720 && /usr/local/rvm/bin/rvm 2.2.1 do passenger -v
DEBUG [cf98ff63]    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'passenger' (>= 0) among 6 total gem(s) (Gem::LoadError)
DEBUG [cf98ff63]    Checked in 'GEM_PATH=/var/www/sites/sitename/shared/bundle/ruby/2.2.0', execute `gem env` for more information
DEBUG [cf98ff63]        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
DEBUG [cf98ff63]        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
DEBUG [cf98ff63]        from /usr/local/rvm/gems/ruby-2.2.1/bin/passenger:22:in `<main>'
DEBUG [cf98ff63]        from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
DEBUG [cf98ff63]        from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

(deploy.rb)
https://gist.github.com/torreyj/c290b0a928027e9b4e76

(deploy/demo.rb)
https://gist.github.com/torreyj/bd8fae6f5a00bd93dffc

(Capfile)
https://gist.github.com/torreyj/05590792231c3ec2b865

**Comment by betesh** [comment]
My first recommendation is to follow the suggestion of the error message: 

```
execute `gem env` for more information
```

**Comment by torreyj** [comment]
I'm pretty sure I did that before I even came here. Thanks for your help. I'll just take this gem off and not use it. Much easier.

**Comment by KarlAmort** [comment]
I'm pretty sure that setting `:passenger_in_gemfile, true` will solve this. It basically prepends 'bundle exec' to those commands, which is what you want if passenger was installed with bundler.

**Comment by betesh** [comment]
I pushed a fix for #26 to master that might solve this too.  @torreyj Let me know if it works.

**Comment by acimadamore** [comment]
I'm having the same issue and i think i found the problem

First my log:
>   INFO ---------------------------------------------------------------------------
  INFO START 2017-03-17 13:27:27 -0300 cap testing passenger:restart
  INFO ---------------------------------------------------------------------------
 DEBUG [cb820a54] Running /usr/bin/env which passenger as root@testing
 DEBUG [cb820a54] Command: ( /usr/bin/env which passenger )
 DEBUG [cb820a54]   /usr/local/rvm/gems/ruby-2.1.4/bin/passenger
 DEBUG [cb820a54] Finished in 1.272 seconds with exit status 0 (successful).
 DEBUG [274e9dc5] Running /usr/local/rvm/bin/rvm version as root@testing
 DEBUG [274e9dc5] Command: ( /usr/local/rvm/bin/rvm version )
 DEBUG [274e9dc5]   rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
 DEBUG [274e9dc5] Finished in 1.348 seconds with exit status 0 (successful).
 DEBUG [427b751d] Running /usr/local/rvm/bin/rvm current as root@testing
 DEBUG [427b751d] Command: ( /usr/local/rvm/bin/rvm current )
 DEBUG [427b751d]   ruby-2.1.4
 DEBUG [427b751d] Finished in 1.892 seconds with exit status 0 (successful).
 DEBUG [b07cd37b] Running /usr/local/rvm/bin/rvm 2.2.3 do ruby --version as root@testing
 DEBUG [b07cd37b] Command: ( /usr/local/rvm/bin/rvm 2.2.3 do ruby --version )
 DEBUG [b07cd37b]   ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
 DEBUG [b07cd37b] Finished in 0.423 seconds with exit status 0 (successful).
 DEBUG [d697f68d] Running if test ! -d /var/www/railsApp/current; then echo "Directory does not exist '/var/www/railsApp/current'" 1>&2; false; fi as root@testing
 DEBUG [d697f68d] Command: if test ! -d /var/www/railsApp/current; then echo "Directory does not exist '/var/www/railsApp/current'" 1>&2; false; fi
 DEBUG [d697f68d] Finished in 0.010 seconds with exit status 0 (successful).
 DEBUG [6750e373] Running /usr/bin/env passenger -v as root@testing
 DEBUG [6750e373] Command: cd /var/www/railsApp/current && ( /usr/bin/env passenger -v )
 DEBUG [6750e373]   /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'passenger' (>= 0) among 8 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/var/www/railsApp/shared/bundle/ruby/2.1.0', execute `gem env` for more information
  from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
  from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
  from /usr/local/rvm/gems/ruby-2.1.4/bin/passenger:22:in `<main>'
  from /usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
 DEBUG [6750e373]     from /usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'

Relevant deploy configuration:
> set :rvm_type, :system
set :rvm_ruby_version, '2.2.3'

My _:rvm_ruby_version_ is the same as the _:passenger_rvm_ruby_version_. My passenger is not in my Gemfile so _:passenger_in_gemfile_ is false. I use the root for deploy(i know is nasty) so i don't need to use _:passenger_restart_with_sudo_.

Some context:
This is a testing server with rvm. We had Rails 4 apps deployed in ruby 2.1.x and passenger 5.0.30, now that we are working on some new Rails 5 apps we installed 2.2.x and Passenger 5.1.2. **Now that i have to deploy with different Ruby versions the problem started.**

I changed my apache2.conf to use passenger 5.1.2 instead of 5.0.30
> LoadModule passenger_module /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.2/buildout/apache2/mod_passenger.so
\<IfModule mod_passenger.c>
  PassengerRoot /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.2
  PassengerDefaultRuby /usr/local/rvm/gems/ruby-2.2.3/wrappers/ruby
\</IfModule>

In every Virtual Host i setted the _PassengerRuby_ accordingly (2.1.x on Rails 4 app and 2.2.x on Rails 5 app).

Debugging i found that the error message corresponds to the _capture(:passenger, '-v')_ on line 20 of _passenger.cap_, the command is not being executed in the rvm environment(_rvm some_version do_) so it fails to found the gem(if you have _:restart_with_touch_ = true this part of the code is skipped that's because you can work around the problem this way).

On the task _passenger:rvm:hook_  _passenger_, _passenger-config_ and _passenger-status_ should be added to the _:rvm_map_bins_ but this is not happening(also this explains why if i execute _gem env_ as the log error suggest i don't see anything wrong, because the gem command is included in the rvm_map_bins)

Why is that? on line 48 of passenger.cap _:passenger_in_path_ has been set true because of the _passenger:test_which_passenger_ task, when it _test(:which, :passenger)_ founds the binstub of my old Passenger 5.0.30 of ruby 2.1.x. 

Correct me if i'm wrong but i think that if i'm using rvm _passenger_, _passenger-config_ and _passenger-status_ should always be prefixed with the _rvm :passenger_rvm_ruby_version do_ that is done on the _passenger:rvm:hook_.

**Comment by betesh** [comment]
Closing due to inactivity.  Please re-open if you feel this is still relevant.
