### ISSUE TITLE
RVM gem not found problem

### ISSUE THREAD

**Issue by pioz** [capistrano/passenger#42]
Im using capistrano-passenger 0.2.0, capistrano 3.8.1 and passenger 5.1.3 in standalone mode.

My deploy.rb contains:

```
set :rvm_ruby_version, 'ruby-2.3.0'
set :passenger_rvm_ruby_version, fetch(:rvm_ruby_version)
set :passenger_in_gemfile, true
```

When I run `cap production deploy` I get the follow error:

```
00:56 passenger:restart
      01 bundle exec passenger-config restart-app /var/sites/teeshirtacademy --ignore-app-not-running
      01 /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find tzinfo-1.2.3 in any of the sources (Bundler::GemNotFoun…
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
      01 	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
      01 	from /home/git/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      01 	from /home/git/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
(Backtrace restricted to imported tasks)

...

** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [7759494d] Command: if test ! -d /var/sites/teeshirtacademy/releases/20170504150957; then echo "Directory does not exist '/var/sites/teeshirtacademy/releases/20170504150957'" 1>&2; false; fi

 DEBUG [7759494d] Finished in 0.266 seconds with exit status 0 (successful).

 DEBUG [a6d32250] Running ~/.rvm/bin/rvm ruby-2.3.0 do bundle exec bundle exec passenger -v as git@megiston.it

 DEBUG [a6d32250] Command: cd /var/sites/teeshirtacademy/releases/20170504150957 && ~/.rvm/bin/rvm ruby-2.3.0 do bundle exec bundle exec passenger -v

 DEBUG [a6d32250] 	Phusion Passenger 5.1.3

 DEBUG [a6d32250] Finished in 2.240 seconds with exit status 0 (successful).

  INFO [00c0589d] Running bundle exec passenger-config restart-app /var/sites/teeshirtacademy --ignore-app-not-running as git@megiston.it

 DEBUG [00c0589d] Command: cd /var/sites/teeshirtacademy/releases/20170504150957 && bundle exec passenger-config restart-app /var/sites/teeshirtacademy --ignore-app-not-running

 DEBUG [00c0589d] 	/home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find tzinfo-1.2.3 in any of the sources (Bundler::GemNotFound)

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'

	from /home/git/.rvm/gems/ruby-2.1.2/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'

	from /home/git/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

	from /home/git/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

Any idea? The task to restart use ruby-2.1.2 but the project run with rvm-2.3.0...

**Comment by betesh** [comment]
> Any idea? The task to restart use ruby-2.1.2 but the project run with rvm-2.3.0...

That's exactly the problem.

Since you've set:
```
set :passenger_in_gemfile, true
```
passenger was installed with ruby 2.3.0

~Try changing `passenger_rvm_ruby_version` to 2.3.0 and see if that fixes it.~ (Whoops, I see that you're already doing that.)

I'm trying to find the solution--give me a few minutes.

**Comment by pioz** [comment]
I've set
```
set :rvm_ruby_version, 'ruby-2.3.0'
set :passenger_rvm_ruby_version, fetch(:rvm_ruby_version)
set :passenger_in_gemfile, true
```
but doesn't work.

**Comment by betesh** [comment]
Try moving those lines into Capfile and let me know what happens.

**Comment by pioz** [comment]
Same problem if i move those lines into Capfile :(

**Comment by betesh** [comment]
What stands out to me as strange is that the `passenger` command is getting `bundle exec` applied to it twice.  Any idea why that would be?

Notice that your output has:
```
cd /var/sites/teeshirtacademy/releases/20170504150957 &&
    ~/.rvm/bin/rvm ruby-2.3.0 do bundle exec bundle exec passenger -v
```
as compared to a few lines later:
```
cd /var/sites/teeshirtacademy/releases/20170504150957 &&
    bundle exec passenger-config restart-app /var/sites/teeshirtacademy --ignore-app-not-running
```

I'm not sure that's a clue, as the real issue is that `rvm` isn't being prepended to the `passenger-config` command, but they may be related.

**Comment by betesh** [comment]
Closing due to inactivity.  Please re-open if you feel this is still relevant.
