### ISSUE TITLE
With multiple processes

### ISSUE THREAD

**Issue by kirykr** [capistrano/passenger#46]
I have read: https://www.phusionpassenger.com/library/walkthroughs/basics/ruby/process_management.html
I have tried running the command `bundle exec passenger start --min-instances 2` in the instance but it raised error as below:
```
=============== Phusion Passenger Standalone web server started ===============
PID file: /var/www/estatedraw-v2/current/tmp/pids/passenger.3000.pid
Log file: /var/www/estatedraw-v2/current/log/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
App 17804 stdout: 
[ 2018-03-12 04:18:17.7180 17761/7f7ad48ce700 age/Cor/SecurityUpdateChecker.h:358 ]: A security update is available for your version (5.1.6) of Passenger, we strongly recommend upgrading to version 5.2.1.
[ 2018-03-12 04:18:17.7180 17761/7f7ad48ce700 age/Cor/SecurityUpdateChecker.h:363 ]:  Additional information: 
- [Fixed in 5.1.11] [URGENT] Users with write access to an application can view arbitrary files on the system if Passenger is running as root.
App 17804 stdout: 
[ 2018-03-12 04:18:20.4553 17761/7f7acc23d700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/estatedraw-v2/current: An error occurred while starting up the preloader.
  Error ID: e9cee348
  Error details saved to: /tmp/passenger-error-CbzdTI.html
  Message from application: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile (LoadError)
  /var/www/estatedraw-v2/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
  /var/www/estatedraw-v2/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
  /var/www/estatedraw-v2/shared/bundle/ruby/2.3.0/gems/activesupport-
--------------

[ 2018-03-12 04:18:20.4617 17761/7f7acd5c9700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is e9cee348. Please see earlier logs for details about the error.
```

**Comment by betesh** [comment]
This is an issue in your Gemfile, not in capistrano-passenger.

Some code is auto-loading this file and triggering this line: https://github.com/rails/rails/blob/v5.1.4/activesupport/lib/active_support/evented_file_update_checker.rb#L59

You need to track down which gem (or possibly your own application code) is doing that and either change its behavior, or add `listen` to a section of your Gemfile that is installed in production.
