### ISSUE TITLE
GemNotFoundException when passenger installed under different ruby

### ISSUE THREAD

**Issue by JSRossiter** [capistrano/passenger#50]
I'm trying to upgrade my ruby version from 2.3.1 to 2.6.3 and this is the error I'm getting:
```
 DEBUG [6a3bd9a7] Command: cd /home/deploy/project/releases/20191209192212 && ( export NODE_ENV="production" ; ~/.rvm/bin/rvm 2.3.1 do passenger -v )

 DEBUG [69be9b5c]       /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem passenger (>= 0.a) (Gem::GemNotFoundException)

        from /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `activate_bin_path'

        from /home/deploy/.rvm/gems/ruby-2.3.1/bin/passenger:23:in `<main>'

        from /home/deploy/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'

        from /home/deploy/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

I'm able to replicate this just running `~/.rvm/bin/rvm 2.3.1 do passenger -v` on the server in the release folder and was able to get it to work running `~/.rvm/bin/rvm 2.3.1 do ruby -S passenger -v` but I don't see a way to modify the command to that

**Comment by betesh** [comment]
Does this work?

`SSHKit.config.command_map.prefix[:passenger].unshift('ruby -S')`

**Comment by JSRossiter** [comment]
Yes, perfect, thanks so much.

For completeness, I added these 3 lines to `deploy.rb`:
```
SSHKit.config.command_map.prefix[:passenger].unshift('ruby -S')
SSHKit.config.command_map.prefix[:'passenger-config'].unshift('ruby -S')
SSHKit.config.command_map.prefix[:'passenger-status'].unshift('ruby -S')
```
